---
title: "Code book"
author: "Liam"
date: "25/02/2021"
output: github_document 
---

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation

Variables used in tidy dataset renamed with:
t = Time
Acc = Acceleration
Gyro = Gyroscope
Mag = Magnitude
std = standard deviation.
---


## List of variables with **descriptive** names

subject : 30 subjects

activity : 6 levels :  
 * WALKING  
 * WALKING_UPSTAIRS  
 * WALKING_DOWNSTAIRS  
 * SITTING  
 * STANDING  
 * LAYING  
                
Time Body Acceleration mean xyz-axis

Time Body Acceleration standard deviation xyz-axis

Time Gravity Acceleration mean xyz-axis 

Time Gravity Acceleration standard deviation xyz-axis           

Time Body Acceleration Jerk mean xyz-axis 

Time Body Acceleration Jerk standard deviation xyz-axis

Time Body Gyroscope mean xyz-axis

Time Body Gyroscope standard deviation xyz-axis

Time Body Gyroscope Jerk mean xyz-axis

Time Body Gyroscope Jerk standard deviation xyz-axis

Time Body Gyroscope Jerk mean xyz-axis 

Time Body Gyroscope Jerk standard deviation xyz-axis 

Time Body Acceleration Magnitude mean

Time Body Acceleration Magnitude standard deviation 

Time Gravity Acceleration Magnitude mean

Time Gravity Acceleration Magnitude standard deviation

Time Body Acceleration Jerk Magnitude mean 

Time Body Gyroscope Magnitude mean

Time Body Gyroscope Magnitude standard deviation 

Time Body Gyroscope Jerk Magnitude mean   

Time Body Gyroscope Jerk Magnitude standard deviation

Frequency Body Acceleration mean xyz-axis

Frequency Body Acceleration standard deviation xyz-axis

Frequency Gravity Acceleration mean xyz-axis 

Frequency Gravity Acceleration standard deviation xyz-axis           

Frequency Body Acceleration Jerk mean xyz-axis 

Frequency Body Acceleration Jerk standard deviation xyz-axis

Frequency Body Gyroscope mean xyz-axis

Frequency Body Gyroscope standard deviation xyz-axis

Frequency Body Gyroscope Jerk mean xyz-axis

Frequency Body Gyroscope Jerk standard deviation xyz-axis

Frequency Body Gyroscope Jerk mean xyz-axis 

Frequency Body Gyroscope Jerk standard deviation xyz-axis 

Frequency Body Acceleration Magnitude mean

Frequency Body Acceleration Magnitude standard deviation 

Frequency Gravity Acceleration Magnitude mean

Frequency Gravity Acceleration Magnitude standard deviation

Frequency Body Acceleration Jerk Magnitude mean 

Frequency Body Gyroscope Magnitude mean

Frequency Body Gyroscope Magnitude standard deviation 

Frequency Body Gyroscope Jerk Magnitude mean   

Frequency Body Gyroscope Jerk Magnitude standard deviation

---

 * The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ
 * These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz
 * The acceleration signal was then separated into body and gravity acceleration signals (Time Body Acceleration-XYZ and tGravityAcc-XYZ)
 * The body linear acceleration and angular velocity were derived in time to obtain Jerk signals (Time Body AccelerationJerk-XYZ and Time BodyGyroJerk-XYZ)
 * The magnitude of these three-dimensional signals were calculated using the Euclidean norm (Time Body AccelerationMag, tGravityAccMag, Time Body AccelerationJerkMag,Time BodyGyroMag, Time BodyGyroJerkMag)
 * A Fast Fourier Transform (FFT) was applied to some of these signals producing Frequency Body  Acceleration-XYZ, Frequency Body  AccelerationJerk-XYZ, Frequency Body Gyro-XYZ, Frequency Body  AccelerationJerkMag, Frequency Body GyroMag, Frequency Body GyroJerkMag. (Note the 'f' to indicate frequency domain signals)
 
The set of variables that were estimated from these signals are: 

mean(): Mean value  
std(): Standard deviation

 